export default [
    {
        id:1,
        name: "Winter Clothe",
        type: "kids-cloth",
        price: "$120",
        image: "/image/k.png",
        image1: "image/k1.png",
        image2: "image/k2.png",
        rating: "⭐⭐⭐⭐⭐",
        reviewAmount: "1203",
        text: "Kids Winter clothes for your child with best offer🤞",
        discountPrice: "$100"
    },
    {
        id:2,
        name: "Winter Jacket",
        type: "kids-cloth",
        price: "$180",
        image: "image/kj.png",
        image1: "image/kj1.png",
        image2: "image/kj2.png",
        rating: "⭐⭐⭐⭐",
        reviewAmount: "987",
        text: "Kids Winter Jacket for your kids we offer here.",
        discountPrice: "$170"
    },
    {
        id:3,
        name: "DELL",
        type: "computers",
        price: "$1299",
        image: "image/c-3.png",
        image1: "image/c-2.png",
        image2: "image/c-1.png",
        rating: "⭐⭐⭐",
        reviewAmount: "123",
        text: "New Dell company Computer with 8th generation processor of core i7",
        discountPrice: "$1250"
    },
    {
        id:4,
        name: "MacBook",
        type: "computers",
        price: "$4000",
        image: "image/c-4.png",
        image1: "image/c-5.png",
        image2: "image/c-6.png",
        rating: "⭐⭐⭐⭐⭐",
        reviewAmount: "5165",
        text: "New Mac book of apple company with 512 SSD, and 16GB ram. core i5 8th",
        discountPrice: "$3800"
    },
    {
        id:5,
        name: "Korean Winter Clothe",
        type: "kids-cloth",
        price: "$190",
        image: "image/k-4.png",
        image1: "image/k-5.png",
        image2: "image/k-6.png",
        rating: "⭐⭐⭐",
        reviewAmount: "15",
        text: "Korean Kids clothes for your kids, with special offer.",
        discountPrice: "$150"
    },
    {
        id:6,
        name: "iPhone",
        type: "mobiles",
        price: "$1299",
        image: "image/m-1.png",
        image1: "image/m-2.png",
        image2: "image/m-3.png",
        rating: "⭐⭐⭐⭐⭐",
        reviewAmount: "1899",
        text: "iPhone 11 pro max with special new year offer id now $1200",
        discountPrice: "$1200"
    },
    {
        id:7,
        name: "A53",
        type: "mobiles",
        price: "$700",
        image: "image/m-4.png",
        image1: "image/m-5.png",
        image2: "image/m-6.png",
        rating: "⭐⭐⭐⭐",
        reviewAmount: "799",
        text: "Samsung galaxy A53 is now available here with special Eid discount",
        discountPrice: "$700"
    },
    {
        id:8,
        name: "Vivo",
        type: "mobiles",
        price: "$500",
        image: "image/m-7.png",
        image1: "image/m-8.png",
        image2: "image/m-9.png",
        rating: "⭐⭐⭐",
        reviewAmount: "300",
        text: "Vico New Mobile is available at singar store.",
        discountPrice: "$450"
    },
    {
        id:9,
        name: "Fruit Mixer",
        type: "home-appliance",
        price: "$240",
        image: "image/h-1.png",
        image1: "image/h-2.png",
        image2: "image/h-3.png",
        rating: "⭐⭐⭐",
        reviewAmount: "30",
        text: "Home Mixer is available here with low price",
        discountPrice: "$230"
    },
    {
        id:10,
        name: "Clothes Dryer",
        type: "home-appliance",
        price: "$670",
        image: "image/h-4.png",
        image1: "image/h-5.png",
        image2: "image/h-6.png",
        rating: "⭐⭐",
        reviewAmount: "456",
        text: "Home Clothes Dryer with low price is here.",
        discountPrice: "$650"
    },
    {
        id:11,
        name: "Refrigerator",
        type: "home-appliance",
        price: "$1000",
        image: "image/h-7.png",
        image1: "image/h-8.png",
        image2: "image/h-9.png",
        rating: "⭐⭐⭐⭐",
        reviewAmount: "883",
        text: "Refrigerator is available with low price here in Singar Store.",
        discountPrice: "$980"
    },
    {
        id:12,
        name: "Office Desk",
        type: "office-appliance",
        price: "$450",
        image: "image/o-1.png",
        image1: "image/o-2.png",
        image2: "image/o-3.png",
        rating: "⭐⭐⭐",
        reviewAmount: "453",
        text: "Office Desk is Now Available here in singar store.",
        discountPrice: "$430"
    },
    {
        id:13,
        name: "Office Printer",
        type: "office-appliance",
        price: "$300",
        image: "image/o-4.png",
        image1: "image/o-5.png",
        image2: "image/o-6.png",
        rating: "⭐⭐⭐⭐⭐",
        reviewAmount: "769",
        text: "Office printer with low price is here.",
        discountPrice: "$290"
    },
    {
        id:14,
        name: "Desk Light",
        type: "office-appliance",
        price: "$150",
        image: "image/o-7.png",
        image1: "image/o-8.png",
        image2: "image/o-9.png",
        rating: "⭐⭐⭐⭐",
        reviewAmount: "121",
        text: "Office Desk is available with low price here in Singar Store.",
        discountPrice: "$145"
    },
]