export default [
    {
        id: 18,
        name: "Malangi Kochi Dress",
        type: "afghani",
        price: "760",
        image: "image/a-7.png",
        image1: "image/a-8.png",
        image2: "image/a-9.png",
        rating: "⭐⭐⭐⭐⭐",
        reviewAmount: "876",
        text: "Vibrant Beauty of Malangi: Introducing the Malangi Afghan Kochi Dress – a mesmerizing blend of culture and artistry. With a burst of vibrant colors and intricate patterns reminiscent of the Afghan heritage, this dress celebrates the spirit of the Malangi region. Each stitch is a testament to the skilled craftsmanship that has been passed down through generations. As you adorn yourself in the Malangi Afghan Kochi Dress, you're not just wearing a garment; you're embracing a piece of history, a tapestry of traditions, and a symbol of individuality. Let the rich stories and captivating designs of the Malangi Afghan Kochi Dress be an extension of your own unique narrative, creating a harmonious fusion of the past and the present.",
        discountPrice: "740"
    },
    {
        id:1,
        name: "Winter Clothe",
        type: "kids-cloth",
        price: "120",
        image: "image/k.png",
        image1: "image/k1.png",
        image2: "image/k2.png",
        rating: "⭐⭐⭐⭐⭐",
        reviewAmount: "1203",
        text: "Introducing our Cozy Kids Winter Clothes Collection: Wrap your little ones in warmth and style with our carefully curated selection of winter essentials. From snugly sweaters that ward off the chill to adorable snowflake-themed jackets that make every snowball fight a delight, our collection is designed to keep your kids cozy and cute all season long. Embrace the magic of winter with our fashion-forward yet practical designs, ensuring your kids stay comfortable and cheerful, no matter how frosty the weather gets.",
        discountPrice: "100"
    },
    {
        id:2,
        name: "Winter Jacket",
        type: "kids-cloth",
        price: "180",
        image: "image/kj.png",
        image1: "image/kj1.png",
        image2: "image/kj2.png",
        rating: "⭐⭐⭐⭐",
        reviewAmount: "987",
        text: "Discover Winter Jacket Perfection: Elevate your child's winter wardrobe with our exquisite range of winter jackets. Crafted with the perfect blend of fashion and function, our jackets offer unparalleled warmth and style for your little adventurers. From sleek and sophisticated designs to fun and playful patterns, our winter jackets ensure your kids stay snug and stylish throughout the chilly season. Explore the joy of winter with confidence, knowing that our jackets are not just garments, but cozy companions for every snowy escapade.",
        discountPrice: "170"
    },
    {
        id:3,
        name: "DELL",
        type: "computers",
        price: "1299",
        image: "image/c-3.png",
        image1: "image/c-2.png",
        image2: "image/c-1.png",
        rating: "⭐⭐⭐",
        reviewAmount: "123",
        text: "Unveiling the Power of Dell Computers: Experience the pinnacle of technology with our exceptional range of Dell computers. Engineered for performance and designed for innovation, our Dell computers redefine your digital experience. From lightning-fast processors to stunning displays, each Dell computer is a gateway to productivity, creativity, and endless possibilities. Whether you're a professional seeking efficiency or a tech enthusiast craving cutting-edge features, our Dell computers cater to every need. Elevate your computing journey today and step into a world where innovation meets reliability, courtesy of Dell.",
        discountPrice: "1250"
    },
    {
        id:4,
        name: "MacBook",
        type: "computers",
        price: "4000",
        image: "image/c-4.png",
        image1: "image/c-5.png",
        image2: "image/c-6.png",
        rating: "⭐⭐⭐⭐⭐",
        reviewAmount: "5165",
        text: "Embark on Limitless Creativity with MacBook: Introducing the iconic MacBook lineup, where innovation meets elegance. Designed to fuel your imagination and empower your endeavors, MacBook offers a seamless fusion of style and performance. With breathtaking Retina displays, powerful processors, and a sleek design that turns heads, our MacBooks redefine what it means to compute in style. Whether you're a designer, a writer, a student, or a visionary, MacBook becomes your canvas for creativity, your gateway to inspiration, and your partner in pursuing excellence. Elevate your digital experience with the brilliance of MacBook and explore new horizons like never before.",
        discountPrice: "3800"
    },
    {
        id:5,
        name: "Korean Winter Clothe",
        type: "kids-cloth",
        price: "190",
        image: "image/k-4.png",
        image1: "image/k-5.png",
        image2: "image/k-6.png",
        rating: "⭐⭐⭐",
        reviewAmount: "15",
        text: "Discover Korean Kids Clothing Delight: Immerse your little ones in the captivating world of Korean fashion with our exquisite collection of kids' clothes. Infused with a touch of Korean charm, our clothing line brings vibrant colors, playful designs, and a unique blend of tradition and modernity. From adorable hanbok-inspired dresses to trendy streetwear, each piece captures the essence of Korean style, allowing your children to express themselves in a whole new way. Elevate their wardrobe with the allure of Korean culture and create cherished memories through fashion that's as distinctive as it is delightful.",
        discountPrice: "150"
    },
    {
        id:6,
        name: "iPhone",
        type: "mobiles",
        price: "1299",
        image: "image/m-1.png",
        image1: "image/m-2.png",
        image2: "image/m-3.png",
        rating: "⭐⭐⭐⭐⭐",
        reviewAmount: "1899",
        text: "Elevate Your Connectivity with iPhone: Introducing the epitome of innovation and sophistication – the iPhone. Seamlessly merging cutting-edge technology with sleek design, our iPhone collection opens the door to a world of possibilities. With stunning displays, powerful cameras, and a seamless ecosystem, each iPhone empowers you to capture moments, stay connected, and experience the digital realm in its purest form. Whether you're capturing memories, staying organized, or immersing yourself in entertainment, the iPhone is your gateway to a universe of convenience and creativity. Explore the future of communication and elevate your mobile experience with the unparalleled brilliance of iPhone.",
        discountPrice: "1200"
    },
    {
        id:7,
        name: "A53",
        type: "mobiles",
        price: "700",
        image: "image/m-4.png",
        image1: "image/m-5.png",
        image2: "image/m-6.png",
        rating: "⭐⭐⭐⭐",
        reviewAmount: "799",
        text: "Experience Brilliance with the Samsung Galaxy A53: Immerse yourself in the world of innovation and style with the Samsung Galaxy A53. Designed to redefine your smartphone experience, the Galaxy A53 boasts a stunning display that brings your content to life with vivid colors and sharp details. Capture the beauty of every moment with the advanced camera system, and enjoy seamless performance for multitasking and entertainment. Whether you're browsing, gaming, or staying connected, the Samsung Galaxy A53 offers a perfect blend of features and aesthetics to enhance your daily life. Elevate your mobile journey and discover the brilliance of the Galaxy A53.",
        discountPrice: "700"
    },
    {
        id:8,
        name: "Vivo",
        type: "mobiles",
        price: "500",
        image: "image/m-7.png",
        image1: "image/m-8.png",
        image2: "image/m-9.png",
        rating: "⭐⭐⭐",
        reviewAmount: "300",
        text: "Introducing the Vivo V21: Embark on a journey of elegance and performance with the Vivo V21. This sleek model boasts an impressive camera setup that captures every detail with clarity, allowing you to document life's moments in stunning quality. With a focus on aesthetics and functionality, the Vivo V21 embodies the essence of modern smartphone excellence.",
        discountPrice: "450"
    },
    {
        id:9,
        name: "Fruit Mixer",
        type: "home-appliance",
        price: "240",
        image: "image/h-1.png",
        image1: "image/h-2.png",
        image2: "image/h-3.png",
        rating: "⭐⭐⭐",
        reviewAmount: "30",
        text: "Revitalize Your Health with the Fruit Mixer: Introducing the ultimate companion for your wellness journey – the Fruit Mixer. Designed to make healthy living a breeze, this versatile appliance transforms fresh fruits and vegetables into delicious and nutrient-packed beverages. Whether you're whipping up a vibrant morning smoothie or experimenting with refreshing juice blends, the Fruit Mixer is your ticket to savoring nature's goodness in every sip. Embrace a lifestyle of vitality and flavor as you create your own culinary masterpieces with the convenience and innovation of the Fruit Mixer.",
        discountPrice: "230"
    },
    {
        id:10,
        name: "Clothes Dryer",
        type: "home-appliance",
        price: "670",
        image: "image/h-4.png",
        image1: "image/h-5.png",
        image2: "image/h-6.png",
        rating: "⭐⭐",
        reviewAmount: "456",
        text: "Effortless Laundry Solutions with the Clothes Dryer: Introducing the modern marvel that simplifies your laundry routine – the Clothes Dryer. Bid farewell to the hassle of air-drying and embrace the convenience of quick and efficient drying right in your home. With advanced technology and customizable settings, the Clothes Dryer ensures your garments emerge fresh, soft, and ready to wear. From delicate fabrics to bulky bedding, this essential appliance takes the guesswork out of drying while saving you time and energy. Elevate your laundry experience and enjoy the luxury of perfectly dried clothes with the reliability and innovation of the Clothes Dryer.",
        discountPrice: "650"
    },
    {
        id:11,
        name: "Refrigerator",
        type: "home-appliance",
        price: "1000",
        image: "image/h-7.png",
        image1: "image/h-8.png",
        image2: "image/h-9.png",
        rating: "⭐⭐⭐⭐",
        reviewAmount: "883",
        text: "Preserve Freshness with the Refrigerator: Welcome to the heart of your kitchen – the Refrigerator. A true marvel of modern convenience, this indispensable appliance keeps your food fresh, your beverages chilled, and your ingredients at the ready. With spacious compartments, temperature control, and innovative features, the Refrigerator ensures your culinary creations are kept in optimal conditions. From storing leftovers to stocking up on groceries, this essential appliance offers a haven for nourishment and inspiration. Embrace the art of preservation and elevate your kitchen experience with the reliability and innovation of the Refrigerator.",
        discountPrice: "980"
    },
    {
        id:12,
        name: "Office Desk",
        type: "office-appliance",
        price: "450",
        image: "image/o-1.png",
        image1: "image/o-2.png",
        image2: "image/o-3.png",
        rating: "⭐⭐⭐",
        reviewAmount: "453",
        text: "Elevate Your Workspace with the Perfect Office Desk: Introducing the cornerstone of productivity and organization – the Office Desk. Crafted to seamlessly blend functionality and aesthetics, our office desks provide a dedicated space where ideas flourish and tasks are conquered. With ample surface area, smart storage solutions, and ergonomic design, our desks transform your workspace into a hub of creativity and efficiency. Whether you're tackling projects, diving into research, or simply organizing your thoughts, our office desks offer the ideal foundation for your professional endeavors. Redefine your work experience and unlock your full potential with the unmatched style and functionality of our meticulously designed office desks.",
        discountPrice: "430"
    },
    {
        id:13,
        name: "Office Printer",
        type: "office-appliance",
        price: "300",
        image: "image/o-4.png",
        image1: "image/o-5.png",
        image2: "image/o-6.png",
        rating: "⭐⭐⭐⭐⭐",
        reviewAmount: "769",
        text: "Enhance Efficiency with the Office Printer: Introducing the engine of productivity for your workspace – the Office Printer. Designed to streamline your document management and communication, our office printers offer swift and high-quality printing solutions. From crisp text to vibrant graphics, each print is a testament to precision and clarity. With versatile connectivity options and user-friendly features, our office printers effortlessly integrate into your workflow, ensuring that important materials are readily available whenever you need them. Embrace the power of efficient printing and elevate your office operations with the reliability and innovation of our cutting-edge office printers.",
        discountPrice: "290"
    },
    {
        id:14,
        name: "Desk Light",
        type: "office-appliance",
        price: "150",
        image: "image/o-7.png",
        image1: "image/o-8.png",
        image2: "image/o-9.png",
        rating: "⭐⭐⭐⭐",
        reviewAmount: "121",
        text: "Illuminate Your Workspace with the Desk Light: Introducing the perfect companion for focused work and creative endeavors – the Desk Light. Crafted to provide optimal lighting conditions, our desk lights brighten your workspace with adjustable brightness levels and directional control. Whether you're reading, writing, or engaging in intricate tasks, our desk lights offer a comfortable and glare-free illumination that reduces eye strain and enhances your productivity. With sleek designs and energy-efficient features, our desk lights effortlessly blend functionality with style, creating an ambiance that inspires your best work. Elevate your workspace and infuse it with the brilliance of our meticulously crafted desk lights – a beacon of light in your journey towards success.",
        discountPrice: "145"
    },
    {
        id:15,
        name: "Kochi Dress",
        type: "afghani",
        price: "330",
        image: "image/a-1.png",
        image1: "image/a-2.png",
        image2: "image/a-3.png",
        rating: "⭐⭐⭐⭐⭐",
        reviewAmount: "345",
        text: "Capture Elegance with the Kochi Dress: Introducing a timeless masterpiece that embodies grace and sophistication – the Kochi Dress. Inspired by the rich cultural heritage of Kochi, this dress is a fusion of tradition and contemporary design, exuding an aura of charm and allure. With intricate embroidery, delicate fabrics, and meticulous craftsmanship, the Kochi Dress celebrates the essence of beauty and cultural diversity. Whether it's a special occasion or a moment of self-expression, this dress is a canvas upon which you can paint your unique story. Elevate your style and immerse yourself in the enchanting world of the Kochi Dress, where elegance knows no bounds.",
        discountPrice: "320"
    },
    {
        id:16,
        name: "Magenta Kochi Dress",
        type: "afghani",
        price: "410",
        image: "image/a-4.png",
        image1: "image/a-5.png",
        image2: "image/a-6.png",
        rating: "⭐⭐⭐⭐",
        reviewAmount: "654 ",
        text: "Elegance in Every Stitch: Introducing the Afghan Magenta Kochi Dress – a true embodiment of opulence and cultural heritage. Crafted with intricate attention to detail, this dress pays homage to the rich traditions of Afghanistan while embracing a contemporary flair. The deep, mesmerizing magenta hue reflects the depth of culture and history, while the traditional embroidery patterns tell stories of generations past. From special occasions to moments of self-expression, the Afghan Magenta Kochi Dress is a timeless masterpiece that gracefully intertwines the old and the new. Elevate your style with a touch of heritage, and let the Afghan Magenta Kochi Dress become a statement of your exquisite taste and appreciation for the art of fashion.",
        discountPrice: "400"
    },
    {
        id:17,
        name: "Shampoo",
        type: "other",
        price: "80",
        image: "image/e-1.png",
        image1: "image/e-2.png",
        image2: "image/e-3.png",
        rating: "⭐⭐⭐",
        reviewAmount: "432",
        text: "Experience Hair Transformation with Our Shampoo: Step into a world of revitalizing beauty with our premium shampoo collection. Crafted with care and expertise, our shampoos are more than just cleansing agents – they're your daily dose of confidence and radiance. Infused with nourishing ingredients and innovative formulas, each wash becomes a rejuvenating ritual, leaving your hair soft, vibrant, and irresistibly touchable. Unleash the potential of your locks and embark on a journey of hair transformation that's as luxurious as it is effective. Elevate your hair care routine with our exquisite shampoos and unlock the secret to hair that shines with life and vitality.",
        discountPrice: "77"
    },
]